[package]
name = "tach"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tach"
crate-type = ["cdylib"]
bench = false

[dependencies]
pyo3 = "0.20.0"
rustpython-parser = "0.3.1"
rustpython-ast = { version = "0.3.1", features = ["visitor"] }
regex = "1.10.4"
once_cell = "1.19.0"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }

[[bench]]
name = "get_project_imports"
harness = false
